### ISSUE TITLE
Fails to verify contract ( err: Unable to locate a contract with the name )

### ISSUE THREAD

**Issue by ShubhamChndrvnshi** [ApeWorX/ape-etherscan#138]
### Environment information

- `ape` and plugin versions:
```
$ ape --version
0.8.2
$ ape plugins list
Installed Plugins
  etherscan    0.8.0
  hardhat      0.8.0
  infura       0.8.0
  solidity     0.8.0
```

- Python Version: 3.9.5
- OS: linux (docker)

### What went wrong?
Tried verifying the contract with ```publish: True```, I got error that it's unable to locate a contract.

- what command you ran
ape run deploy_cicada --network :sepolia:infura ( This is a script to deploy a contract named PrivateVote under src/PrivateVote.sol )
- the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
```
import click
from ape import project, networks, accounts
from ape.cli import (
    ConnectedProviderCommand,
    network_option,
    ape_cli_context,
)
    
@click.command(cls=ConnectedProviderCommand)
@ape_cli_context()
@network_option()
def cli(cli_ctx, network):
    """
    Get public parameter of cicada vote instance
    """
    try:
        # custom gas fee
        max_fee = '200 gwei'
        max_priority_fee = '10 gwei'
        # Check network details
        ecosystem_name = networks.provider.network.ecosystem.name
        network_name = networks.provider.network.name
        provider_name = networks.provider.name

        click.secho(f"Selected network: {network_name}", fg="blue")

        account = accounts.load("olas")

        click.secho(
            f"You are connected to network '{ecosystem_name}:{network_name}:{provider_name}'.",
            fg="yellow",
        )
        click.secho(f"Deployer is set to '{account}'.", fg="yellow")
        
        # Deploy the contract
        click.secho("Deploying the PrivateVote contract...", fg="green")
        project.PrivateVote.deploy(sender=account, publish=True, max_fee=max_fee, max_priority_fee=max_priority_fee)
        click.secho("Contract deployed successfully!", fg="green")
    except Exception as e:
        click.secho(f"An error occurred: {e}", fg="red")
```
- full output of the error you received
```
Unable to verify. Unable to locate a contract with the name 'PrivateVote.sol:PrivateVote', did you specify the correct Contract Name?
```
Have attached a txt file that contains the output from terminal for command run with ```-v DEBUG```
[debug.txt](https://github.com/user-attachments/files/16077730/debug.txt)

### How can it be fixed?

Fill this in if you have ideas on how the bug could be fixed.

**Comment by antazoey** [comment]
As an aside, there are some things with your script I want to comment on!

1. Since 0.7.0, you no longer need to specify `@network_option()` with `ConnectedProviderCommand`, you get it automatically and it works better without it
2. When using `ConnectedProviderCommand`, you can also accept `provider` and `ecosystem` right in the command args,

Here is an example!

```python
@click.command(cls=ConnectedProviderCommand)
@ape_cli_context()
def cli(cli_ctx, ecosystem, network, provider):
         ...
        # No need for lines like `network_name = networks.provider.network.name`
        click.secho(f"Selected network: {network.name}", fg="blue")
```

(Partially shilling this feature)

**And also, for the record, I am looking into the issue now and working on ape-etherscan as a whole**

**Comment by antazoey** [comment]
fixed by https://github.com/ApeWorX/ape-etherscan/pull/140

**Comment by ShubhamChndrvnshi** [comment]
Worked for me
https://sepolia.etherscan.io/address/0xd9aaBA4a0Cf1F087cEc266e2811e8ae5cAb1Faf3#code
