### ISSUE TITLE
No contract type found when using mainnet-fork

### ISSUE THREAD

**Issue by r4VP4** [ApeWorX/ape-etherscan#19]
### Environment information

* `ape` and plugin versions:

```
$ ape --version
0.2.2

$ ape plugins list
  etherscan    0.2.0
  hardhat      0.2.0
  solidity     0.2.2
  alchemy      0.2.0

```

* Python Version: 3.9.9 (pyenv)
* OS: linux

### What went wrong?

I am trying to initiate an erc20 contract like this:
contract = Contract('0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2')
But i get a warning: WARNING: No contract type found for 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
this problem occurs only if i am using a mainnet-fork. when connecting to mainnet everything's fine

**Comment by r4VP4** [comment]
it's working. thank you!!

**Comment by fubuloubu** [comment]
released in https://github.com/ApeWorX/ape-etherscan/releases/tag/v0.2.1
