### ISSUE TITLE
feat: please support etherscan api key

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape-etherscan#3]
### Overview

Provide a simple overview of what you wish to see added. Please include:

* What you are trying to do: use the etherscan api key
* Why Ape's current functionality is inadequate to address your goal: does not have etherscan api key ability

### Specification

maybe pull from environment variable? 

### Dependencies

none

**Comment by fubuloubu** [comment]
note: we should make sure the `config` object can handle this scenario of loading environment variables as well
