### ISSUE TITLE
feat: support additional explorers

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape-etherscan#4]
### Overview

Provide a simple overview of what you wish to see added. Please include:

* What you are trying to do: use this plugin with other networks and other explorers
* Why Ape's current functionality is inadequate to address your goal: currently only supports etherscan

### Specification

This should support bscscan and polygonscan etc

### Dependencies

n/a

**Comment by fubuloubu** [comment]
because etherscan has a bunch of different explorers they are also maintaining using the same basic API, it might make sense to just "Extend" by subclassing `Etherscan` with some modifications for how the URI is set

**Comment by fubuloubu** [comment]
also FtmScan

**Comment by sabotagebeats** [comment]
since we now have ftmscan I'm going to close this issue. @fubuloubu
